### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by ghost** [RubenPonce/Delete-Your-Youtube-Comments#4]
![obraz](https://user-images.githubusercontent.com/37625981/86522670-ce45af80-be61-11ea-8143-fc7c5355d185.png)

**Comment by RubenPonce** [comment]
Just tested it out on Chrome right now and its working.  Are you using Chrome and copy paste the code into dev tools console?

**Comment by overmighty** [comment]
I get the same error on Chromium 84.0.4147.89.
