### ISSUE TITLE
doesnt work 2022

### ISSUE THREAD

**Issue by DE0ZA** [RubenPonce/Delete-Your-Youtube-Comments#6]
Insanely helpful tool if it worked. Im thinking of deleting my youtube account because of the comments ive made and they are so many. Would be really nice if you updated the tool.

**Comment by TheToto** [comment]
This very hacky and brutal scripts works, after some manual deletion (which open a modal), next deletion will just need to click on the delete button, so it spam them.


I don't known if the class names are account specific.

```
setInterval(() => {
  setTimeout(() => window.scrollTo(0, document.body.scrollHeight), 1000);
setTimeout(() => { [...document.querySelectorAll("c-wiz .GqCJpe.u2cbPc.LDk2Pd .VfPpkd-Bz112c-LgbsSe.yHy1rc.eT1oJ.mN1ivc")].forEach(node => node.click()); } )
}, 5000) 
```

**Comment by TheToto** [comment]
This hacky script will work after few manual deletion (when there is no more modals).
Class names may be differ though.
```
let sleep = time => new Promise(res => setTimeout(res, time, "done sleeping"));

async function work() {
  let buttons = [...document.querySelectorAll("c-wiz .GqCJpe.u2cbPc.LDk2Pd .VfPpkd-Bz112c-LgbsSe.yHy1rc.eT1oJ.mN1ivc")];
  console.log("Deleting " + buttons.length + " comments");
	for (let b of buttons) {
    console.log("Hit");
    b.click();
    await sleep(2000);
  }
  console.log("End. Scrolling...")
  window.scrollTo(0, document.body.scrollHeight);
}

async function run() {
  while (true) {
    await work();
    await sleep(10000);
  }
}

run();
```

**Comment by RubenPonce** [comment]
Updating the script with that. Sorry feel free to fork as I'm not maintaining this repo.
